-- VISTA POR DETALLE DE RUTA Y MES

SELECT 	
	T0.ARTICULO,
	CONVERT(DECIMAL(7,2),COUNT(T0.ARTICULO)) cArticulo,
	CONVERT(DECIMAL(7,2),COUNT(COUNT(T0.ARTICULO)) over ()) cttArticulo,
	((CONVERT(DECIMAL(7,2),COUNT(T0.ARTICULO)) /  CONVERT(DECIMAL(7,2),COUNT(COUNT(T0.ARTICULO)) over ()) ) * 100 ) Aporte
FROM Softland.dbo.ANA_VentasTotales_MOD_Contabilidad_UMK T0 
WHERE T0.VENDEDOR = 'F03'  
AND YEAR ( T0.Fecha_de_factura ) = '2022' 
AND MONTH ( T0.Fecha_de_factura ) = '2' 
AND t0.VentaNetaLocal  > 0
AND t0.ARTICULO NOT LIKE 'VU%'
GROUP BY T0.ARTICULO
ORDER BY COUNT(T0.ARTICULO) DESC